version: "3.7"

services:
  app:
    build: .
    container_name: app
    command:  uvicorn src.api:app --host 0.0.0.0
    ports:
      - 8000:8000
    depends_on:
      - "db"

  db:
    image: postgres:12.1-alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}